services:
  database:
    image: mysql:8
    environment:
      DB_HOST: containername
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    ports:
      - "3306:3306"

  backend:
    build: ./api
    depends_on: [database]
    ports:
      - "3000:3000"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"

  adminer:
    ports:
      - "8081:8081"

volumes:
  db_data:
